config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

 # get 'books' => 'books#index'
  #get 'books/:id' => 'books#show'
  
  resources :publications
  

  resources :books do
    resources :editions
  end
  
  
  
end

app/models/address.rb
class Address < ApplicationRecord
  belongs_to :common_user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, :author_name, :language, :category, presence: true 

  has_many :editions
  has_many :publications, :through => :editions
  
end

app/models/branch.rb
class Branch < ApplicationRecord
  belongs_to :common_user
end

app/models/common_user.rb
class CommonUser < ApplicationRecord
  has_many :addresses
  has_many :branches
  has_many :feedback_tables
  has_many :feedback_tables , as: :sender
end

app/models/edition.rb
class Edition < ApplicationRecord
  belongs_to :book
  belongs_to :publication
  has_many :feedback_tables , as: :sender

  validates :version, :count, :published_date, :cover_type, :no_of_pages, :price,
    :book_id, :publication_id, presence: true
  validates :cover_type ,inclusion: { in: ['Paper Back', 'Hard Cover'] }
  before_save :initialize_count

  def initialize_count
    self.count = 0 unless self.count
  end
end

app/models/feedback_table.rb
class FeedbackTable < ApplicationRecord

  belongs_to :sender, polymorphic: true
end

app/models/publication.rb
class Publication < ApplicationRecord
  has_many :editions
  has_many :books, :through => :editions
  has_many :feedback_tables , as: :sender

  validates :name, :email, :mobile_number, presence: true
  validates :mobile_number, length: {is: 10}

  after_create :remove_spaces

  def remove_spaces
    self.mobile_number = self.mobile_number.gsub(" ","")
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  before_action :find_book, only: [:show, :destroy, :edit, :update]

  def index
    @books = Book.all.includes(:editions)
    #render json: @books
  end

  def show
   # render json: @book
  end

  def new
    
  end

  def edit
    book_id = params['id']
    @book_edit = Book.find_by_id(book_id)
  end

  def update
  
    if @book.update_attributes(params
                          .require('book')
                          .permit(:title, :author_name, :category, :language))
      render json: @book
    else
      render json: @book.errors, status: :unprocessable_entity                      
    end                        
  end

  def create
    puts "\n\n #{params} \n \n"
    @book = Book.new
    @book.title = params["title"]
    @book.author_name = params["author_name"]
    @book.language = params["language"]
    @book.category = params["category"]
    puts "\n\n #{@book} \n \n"
   
    if @book.save
      render json: @book, status: :created, location: @book
    else
      render json: @book.errors, status: :unprocessable_entity
    end
    
  end

  def destroy
    @book.editions.delete
    @book.delete
    
    redirect_to '/books'
  end

  def find_book
    book_id = params[:id]
    @book = Book.find_by_id(book_id)
   # @book_edition = Book.joins("INNER JOIN editions ON editions.book_id = #{book_id}")
  end
end

app/controllers/editions_controller.rb
class EditionsController < ApplicationController

#  def index
#    render json: Edition.all
#  end

  def  new
    @edition_data = Edition.new
  end

  def edit
   
    @edition_edit = Edition.find_by_id(params[:id])
  end
  


  def show 
    @book = Book.find_by_id(params[:book_id])
    @edition_id = Edition.find_by_id(params[:id])
    @publication = @edition_id.publication  
   # render json: @edition_id
  end
  
  def update
    edition_edit = Edition.find_by_id(params[:id])
    if edition_edit.update_attributes(params
                                .require('edition')
                                .permit(:version, :published_date, :cover_type,
                                :no_of_pages, :price, :count, 
                                :publication_id)
                              )
    else
      render json: @edition_edit.errors, status: :unprocessable_entity                      
    end              
  end

  def create
    puts "In create method Edition Controller"
    @book = Book.find_by_id(params[:book_id])
    
    @edition = @book.editions.create(params
                                      .require('edition')
                                      .permit(:version, :published_date, :cover_type,
                                       :no_of_pages, :price, :count, 
                                       :publication_id)

                                      )

    if @edition
      render json: @book, status: :created, location: @book
    else
      render json: @book.errors, status: :unprocessable_entity
    end
    
    #p @edition.errors
  end

  def destroy
    @edition = Edition.find_by_id(params[:id])
    @edition.delete
    redirect_to "/books/#{params[:book_id]}"
  end
end

app/controllers/publications_controller.rb
class PublicationsController < ApplicationController

  def index
    @publications = Publication.all
  end

  def destroy
    publication_id = params[:id]
    Publication.find_by(publication_id).delete
  end

  def show
    publication_id = params[:id]
    p @publication = Publication.find_by_id(publication_id)
  end

  def new
    @publication_data = Publication.new
  end

  def create
    publication_id = params[:id]
    @publication = Publication.create(params
                                      .require(:publication)
                                      .permit(
                                        :name,
                                        :email,
                                        :mobile_number))
    if @publication
      render json: @publication, status: :created, location: @publication
    else
      render json: @publication.errors, status: :unprocessable_entity
    end
  end


  def edit
    publication_id = params[:id]
    @publication_edit = Publication.find_by_id(publication_id)
  end

  def update
    @publication_edit = Publication.find_by_id(params[:id])
    if @publication_edit.update_attributes(params
                              .require('publication')
                              .permit(:name, :email, :mobile_number))
      render json: @publication_edit
    else
      render json: @publication_edit.errors, status: :unprocessable_entity                      
    end                        
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/editions_helper.rb
module EditionsHelper
end

app/helpers/publication_helper.rb
module PublicationHelper
end

app/views/books/create.html.erb
<h1>HEYYYYYYYYYYy</h1>

app/views/books/edit.html.erb
<h1>Edit Book</h1>

<div>
    <%= form_for @book_edit, url: { action: "update" } do |book_form| %>
    <table>
     <tbody>
        <tr>
            <td> <%= label_tag(:title, " Id : ") %></td>
            <td>  <%= book_form.text_field :id %> </td>
           </tr>
            
        <tr>
         <td> <%= label_tag(:title, " Title : ") %></td>
         <td>  <%= book_form.text_field :title %></td>
        </tr>
     
        <tr>
          <td>  <%= label_tag(:category, " Category : ") %></td>
          <td>   <%= book_form.text_field :category %></td>
         </tr>
  
         <tr>
          <td> <%= label_tag(:author_name, " Author Name : ") %></td>
          <td> <%= book_form.text_field :author_name %> </td>
         </tr>
        
         <tr>
          <td>  <%= label_tag(:language, " Language : ") %></td>
          <td>  <%= book_form.text_field :language %> </td>
         </tr>
         
         <tr>
           <td></td>
           <td> <%= submit_tag 'Edit' %></td> 
         </tr>
          <% end %>
        </tbody>
    </table>
</div>

app/views/books/index.html.erb
<h1> Books Store Application </h1>
<div>
  <%= button_to "Add Book", { :action => "new" }, :method => :get %>
  <%= button_to "Add Publication", new_publication_path, :method => :get %>
</div>
<hr>
<div>
 
  <table>
    <thead>
      <tr>
        <th>&nbsp;</th>
          <th> Book Title</th>
          <th> Actions</th>
          <th> Editions</th>
      </tr>
    </thead>
    <tbody>
      <% @books.each do |book| %>
        <tr>
          <td>&nbsp;</td>
          <td><p> <%=book.title%></p></td>
          <td><p>
          <%= link_to "View", book_path(book), :id => 'view', :method => :get %>
          <%= link_to "Edit", edit_book_path(book),:id => 'edit', :method => :get %>  
          <%= link_to "Delete", book_path(book),:id => 'delete', :method => :delete %>
          <%= link_to "Add Edition", new_book_edition_path(book),:id => "new", :method => :get %>
          </p> </td>  
          <td>
            <%book.editions.each do |edition| %>
              <p><%=edition.version%>  <%=edition.published_date%></p>
            <%end%>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/books/new.html.erb
<h1> Create Book</h1>
  <br>
  <br>
<div>
  <%= form_with(url: "/books", method: "post") do %>
  <%= field_set_tag 'Book details', class: 'fieldset_width' do %>
  <table>
   <tbody>    
      
      <tr>
       <td> <%= label_tag(:title, " Title : ") %></td>
       <td>  <%= text_field_tag(:title) %> </td>
      </tr>
   
      <tr>
        <td>  <%= label_tag(:category, " Category : ") %></td>
        <td>   <%= text_field_tag(:category) %> </td>
       </tr>

       <tr>
        <td> <%= label_tag(:author_name, " Author Name : ") %></td>
        <td> <%= text_field_tag(:author_name) %> </td>
       </tr>
      
       <tr>
        <td>  <%= label_tag(:language, " Language : ") %></td>
        <td>  <%= text_field_tag(:language) %></td>
       </tr>
      
      </tbody>
    </table>
    <% end %>
<br>
       <%= field_set_tag 'Edition details', class: 'fieldset_width' do %>
       <table>
          <tbody>  
       <tr>
        <td> <%= label_tag(:version, " Version : ") %></td>
        <td>  <%= text_field_tag(:version) %> </td>
       </tr>
    
       <tr>
         <td>  <%= label_tag(:published_date, " Published Date : ") %></td>
         <td>   <%= text_field_tag(:published_date) %> </td>
        </tr>
 
        <tr>
         <td> <%= label_tag(:cover_type, " Cover Type: ") %></td>
         <td> <%= text_field_tag(:cover_type) %> </td>
        </tr>
       
        <tr>
         <td>  <%= label_tag(:no_of_pages, " No of Pages : ") %></td>
         <td>  <%= text_field_tag(:no_of_pages) %></td>
        </tr>
        
        <tr>
           <td>  <%= label_tag(:price, " Price : ") %></td>
           <td>  <%= text_field_tag(:price) %></td>
        </tr>
 
        <tr>
           <td>  <%= label_tag(:count, " Count : ") %></td>
           <td>  <%= text_field_tag(:count) %></td>
        </tr>
 
        <tr>
           <td>  <%= label_tag(:publication_id, " Publication : ") %></td>
           <td>  <%= select("name", 
                           "publication_id", 
                           Publication.all.collect { |p| [ p.name, p.id ] },
                           { include_blank: true }) 
                 %>
           </td>
        </tr>
        <% end %>



       <tr>
         <td></td>
         <td><%= submit_tag("Create") %></td> 
       </tr>
        <% end %>
      </tbody>
  </table>

</div>

app/views/books/show.html.erb
<h1> Details of Book </h1>
<h3>Id : <%= @book.id%></h3>
<h3>Title : <%= @book.title %></h3>
<h3>Author : <%= @book.author_name%></h3>
<h3>Category : <%= @book.category%></h3>
<h3>Language : <%= @book.language%></h3>

<h1> Book Editions</h1>
<hr>
<%@book.editions.each do |edition| %>
<h3> Version : <%=edition.version%></h3>  
<h3> Published Date : <%=edition.published_date%></h3>
<h3> Cover Type : <%=edition.cover_type%></h3>
<h3> No of Pages : <%=edition.no_of_pages%></h3>
<h3> Price : <%=edition.price%></h3>
<%= link_to "View Edition", book_edition_path(@book, edition), :id => 'view', :method => :get %>
<%= link_to "Edit Edition", edit_book_edition_path(@book, edition), :id => 'edit', :method => :get %>
<%= link_to "Delete", book_edition_path(@book, edition),:id => 'delete', :method => :delete %>
<hr>
<%end%>

app/views/editions/edit.html.erb
<h1>Edit Edition</h1>

<div>
    <%= form_for @edition_edit, url: { action: "update" } do |edition_form| %>
    <table>
     <tbody>
        <tr>
            <td> <%= label_tag(:title, " Id : ") %></td>
            <td>  <%= edition_form.text_field :id %> </td>
         </tr>
            
        <tr>
         <td> <%= label_tag(:version, " Version : ") %></td>
         <td>  <%= edition_form.text_field :version %></td>
        </tr>
     
        <tr>
          <td>  <%= label_tag(:published_date, " Published Date : ") %></td>
          <td>   <%= edition_form.text_field :published_date %></td>
         </tr>
  
         <tr>
          <td> <%= label_tag(:cover_type, " Cover Type: ") %></td>
          <td> <%= edition_form.text_field :cover_type %> </td>
         </tr>
        
         <tr>
          <td> <%= label_tag(:no_of_pages, " No of Pages : ") %></td>
          <td>  <%= edition_form.text_field :no_of_pages %> </td>
         </tr>
         
         <tr>
            <td>  <%= label_tag(:price, " Price : ") %></td>
            <td>   <%= edition_form.text_field :price %> </td>
         </tr>
  
         <tr>
            <td>  <%= label_tag(:count, " Count : ") %></td>
            <td>   <%= edition_form.text_field :count %> </td>
         </tr>
  
         <tr>
            <td>  <%= label_tag(:publication_id, " Publication : ") %></td>
            <td>  <%= edition_form.collection_select :publication_id, 
                                             Publication.all, :id, :name,
                                              {:prompt => @select_value, 
                                             :selected => @edition_edit.publication_id.to_i}
                  %>
            </td>
         </tr>
         <tr>
           <td></td>
           <td> <%= submit_tag 'Edit' %></td> 
         </tr>
          <% end %>
    
        </tbody>
    </table>
</div>

app/views/editions/new.html.erb
<h1> Create Edition</h1>
  <br>
  <br>
<div>
  <%= form_for @edition_data, url:{ action: "create" } do |edition_form| %>
  <table>
   <tbody>    
      <tr>
       <td> <%= label_tag(:version, " Version : ") %></td>
       <td>  <%= edition_form.text_field(:version) %> </td>
      </tr>
   
      <tr>
        <td>  <%= label_tag(:published_date, " Published Date : ") %></td>
        <td>   <%= edition_form.text_field(:published_date) %> </td>
       </tr>

       <tr>
        <td> <%= label_tag(:cover_type, " Cover Type: ") %></td>
        <td> <%= edition_form.text_field(:cover_type) %> </td>
       </tr>
      
       <tr>
        <td>  <%= label_tag(:no_of_pages, " No of Pages : ") %></td>
        <td>  <%= edition_form.text_field(:no_of_pages) %></td>
       </tr>
       
       <tr>
          <td>  <%= label_tag(:price, " Price : ") %></td>
          <td>  <%= edition_form.text_field(:price) %></td>
       </tr>

       <tr>
          <td>  <%= label_tag(:count, " Count : ") %></td>
          <td>  <%= edition_form.text_field(:count) %></td>
       </tr>

       <tr>
          <td>  <%= label_tag(:publication_id, " Publication : ") %></td>
          <td>  
                <%= edition_form.collection_select :publication_id, Publication.all, :id, :name %>                   
          </td>
       </tr>

       <tr>
         <td></td>
         <td><%= submit_tag("Create") %></td> 
       </tr>
        <% end %>
      </tbody>
  </table>

</div>

app/views/editions/show.html.erb
<h1> Details of Book </h1>
<h3>Id : <%= @book.id%></h3>
<h3>Title : <%= @book.title %></h3>
<h3>Author : <%= @book.author_name%></h3>
<h3>Category : <%= @book.category%></h3>
<h3>Language : <%= @book.language%></h3>

<h1> Book Editions</h1>
<hr>
<%@book.editions.each do |edition| %>
<h3> Version : <%=edition.version%></h3>  
<h3> Published Date : <%=edition.published_date%></h3>
<h3> Cover Type : <%=edition.cover_type%></h3>
<h3> No of Pages : <%=edition.no_of_pages%></h3>
<h3> Price : <%=edition.price%></h3>
<%= link_to "View Edition", book_edition_path(@book, edition), :id => 'view', :method => :get %>
<%= link_to "Edit Edition", edit_book_edition_path(@book, edition), :id => 'edit', :method => :get %>
<%= link_to "Delete", book_edition_path(@book, edition),:id => 'delete', :method => :delete %>
<hr>
<%end%>

<h1> Details of Publication </h1>
<h3>Id : <%= @publication.id%></h3>
<h3>Title : <%= @publication.name %></h3>
<h3>Author : <%= @publication.email%></h3>
<h3>Mobile No : <%= @publication.mobile_number%></h3>
<%= link_to "Edit", edit_publication_path(@publication),:id => "edit", :method => :get %>
<%= link_to "Delete", publication_path(@publication),:id => 'delete', :method => :delete %>
<hr>

app/views/editions/update.html.erb
<div>
  <h1> Value got Updated</h1>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookstore</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/publications/edit.html.erb
<h1>Edit Book</h1>

<div>
    <%= form_for @publication_edit, url: { action: "update" } do |publication_form| %>
    <table>
     <tbody>
        <tr>
            <td> <%= label_tag(:id, " Id : ") %></td>
            <td>  <%= publication_form.text_field :id %> </td>
         </tr>
            
        <tr>
         <td> <%= label_tag(:name, " Name : ") %></td>
         <td>  <%= publication_form.text_field :name %></td>
        </tr>
     
        <tr>
          <td>  <%= label_tag(:email, " Email : ") %></td>
          <td>   <%= publication_form.text_field :email %></td>
         </tr>
  
         <tr>
          <td> <%= label_tag(:mobile_number, " Mobile No: ") %></td>
          <td> <%= publication_form.text_field :mobile_number %> </td>
         </tr>
        
       
         <tr>
           <td></td>
           <td> <%= submit_tag 'Edit' %></td> 
         </tr>
          <% end %>
    
        </tbody>
    </table>
</div>

app/views/publications/index.html.erb
<h1>Publication List</h1>
<div>
  <% @publications.each do |publication| %>
    <p> <%=publication.id%></p> <br>
    <p> <%=publication.name%></p> <br>
    <p> <%=publication.email%></p> <br>
    <p> <%=publication.mobile_number%></p> <br>
  <%end%>
</div>

app/views/publications/new.html.erb
<h1> Create Publication</h1>
  <br>
  <br>
<div>
  <%= form_for @publication_data, url:{ action: "create" } do |publication_form| %>
  <table>
   <tbody>    
      <tr>
       <td> <%= label_tag(:name, " Name : ") %></td>
       <td>  <%= publication_form.text_field(:name) %> </td>
      </tr>
   
      <tr>
        <td>  <%= label_tag(:email, " Email : ") %></td>
        <td>   <%= publication_form.text_field(:email) %> </td>
       </tr>

       <tr>
        <td> <%= label_tag(:mobile_number, " Mobile No : ") %></td>
        <td> <%= publication_form.text_field(:mobile_number) %> </td>
       </tr>
      
       <tr>
         <td></td>
         <td><%= submit_tag("Create") %></td> 
       </tr>
        <% end %>
      </tbody>
  </table>

</div>

app/views/publications/show.html.erb
<h1> Publication </h1>
<div>
  <p> <%=@publication.id%></p> <br>
  <p> <%=@publication.name%></p> <br>
  <p> <%=@publication.email%></p> <br>
  <p> <%=@publication.mobile_number%></p> <br>
 
 
</div>